//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLSS_Swapper.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLSS_Swapper.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Acknowledgements.
        /// </summary>
        public static string Acknowledgements {
            get {
                return ResourceManager.GetString("Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Cover.
        /// </summary>
        public static string AddCover {
            get {
                return ResourceManager.GetString("AddCover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Custom Cover.
        /// </summary>
        public static string AddCustomCover {
            get {
                return ResourceManager.GetString("AddCustomCover", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Game.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error adding your game.
        /// </summary>
        public static string AddingGameError {
            get {
                return ResourceManager.GetString("AddingGameError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu There was a problem and your game could not be added at this time. Please report this issue..
        /// </summary>
        public static string AddingGameErrorReportIssue {
            get {
                return ResourceManager.GetString("AddingGameErrorReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Another note for manually adding games.
        /// </summary>
        public static string AddingGamesManuallyAnotherNote {
            get {
                return ResourceManager.GetString("AddingGamesManuallyAnotherNote", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DLSS Swapper should find games from your installed game libraries automatically. If your game is not listed there may be a few settings preventing it. Please check:
        ///
        ///- Games list filter is not set to &quot;Hide games with no swappable items&quot;
        ///- Specific game library is enabled in settings
        ///
        ///If you have checked these and your game is still not showing up there may be a bug. We would appreciate it if you could report the issue on our GitHub repository so we can make a fix and have your games better detected in  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string AddingGamesManuallyNote {
            get {
                return ResourceManager.GetString("AddingGamesManuallyNote", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Note for manually adding games.
        /// </summary>
        public static string AddingGamesManuallyNoteTitle {
            get {
                return ResourceManager.GetString("AddingGamesManuallyNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This app is running with administrative privileges..
        /// </summary>
        public static string ApplicationRunsInAdministrativeModeInfo {
            get {
                return ResourceManager.GetString("ApplicationRunsInAdministrativeModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DLSS Swapper.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Shown below are the multiple DLLs found. You will still be able to swap and restore DLLs as usual as we will do these actions to all DLLs at once. However because we don&apos;t know what one of these DLLs is used by the game the DLL version shown is of the first DLL detected..
        /// </summary>
        public static string BelowMultipleDllFoundYouWillBeAbleToSwapInfo {
            get {
                return ResourceManager.GetString("BelowMultipleDllFoundYouWillBeAbleToSwapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Click to copy below details.
        /// </summary>
        public static string ClickToCopyDetails {
            get {
                return ResourceManager.GetString("ClickToCopyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not find file &quot;{0}&quot;..
        /// </summary>
        public static string CouldNotFindFileTemplate {
            get {
                return ResourceManager.GetString("CouldNotFindFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not find path &quot;{0}&quot;..
        /// </summary>
        public static string CouldNotFindGameInstallPathTemplate {
            get {
                return ResourceManager.GetString("CouldNotFindGameInstallPathTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not open your log file directly from DLSS Swapper. Please try open it manually..
        /// </summary>
        public static string CouldNotOpenLogFileTryManual {
            get {
                return ResourceManager.GetString("CouldNotOpenLogFileTryManual", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not download at this time..
        /// </summary>
        public static string CouldntDownloadNow {
            get {
                return ResourceManager.GetString("CouldntDownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not export DLSS dll..
        /// </summary>
        public static string CouldntExportDlssDll {
            get {
                return ResourceManager.GetString("CouldntExportDlssDll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create new GitHub issue.
        /// </summary>
        public static string CreateNewGithubIssue {
            get {
                return ResourceManager.GetString("CreateNewGithubIssue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current DLL.
        /// </summary>
        public static string CurrentDll {
            get {
                return ResourceManager.GetString("CurrentDll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete {0} v{1}?.
        /// </summary>
        public static string DeleteDllVersionTemplate {
            get {
                return ResourceManager.GetString("DeleteDllVersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Diagnostics.
        /// </summary>
        public static string Diagnostics {
            get {
                return ResourceManager.GetString("Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DLSS Swapper has failed to launch.
        /// </summary>
        public static string DlssSwapperFailedToLaunch {
            get {
                return ResourceManager.GetString("DlssSwapperFailedToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Don&apos;t show again.
        /// </summary>
        public static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Download Error.
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enabled for all DLSS DLLs.
        /// </summary>
        public static string EnabledForAllDlssDlls {
            get {
                return ResourceManager.GetString("EnabledForAllDlssDlls", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enabled for debug DLSS DLLs only.
        /// </summary>
        public static string EnabledForDebugDlssDllOnly {
            get {
                return ResourceManager.GetString("EnabledForDebugDlssDllOnly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable logging to file.
        /// </summary>
        public static string EnableLoggingToFile {
            get {
                return ResourceManager.GetString("EnableLoggingToFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export All.
        /// </summary>
        public static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exported DLL {0}..
        /// </summary>
        public static string ExportedDll {
            get {
                return ResourceManager.GetString("ExportedDll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exported {0} DLSS dll{1}..
        /// </summary>
        public static string ExportedDllsTemplate {
            get {
                return ResourceManager.GetString("ExportedDllsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not export due to &quot;{0}&quot; having {1} dlls instead of 1..
        /// </summary>
        public static string ExportErrorDueToDllsCountTemplate {
            get {
                return ResourceManager.GetString("ExportErrorDueToDllsCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to Launch.
        /// </summary>
        public static string FailedToLaunch {
            get {
                return ResourceManager.GetString("FailedToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This game is not in a ready to play state..
        /// </summary>
        public static string GameNotReadyToPlayState {
            get {
                return ResourceManager.GetString("GameNotReadyToPlayState", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (GitHub account required).
        /// </summary>
        public static string GithubAccountRequired {
            get {
                return ResourceManager.GetString("GithubAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grid View.
        /// </summary>
        public static string GridView {
            get {
                return ResourceManager.GetString("GridView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Group games from the same library together.
        /// </summary>
        public static string GroupGamesFromTheSameLibraryTogether {
            get {
                return ResourceManager.GetString("GroupGamesFromTheSameLibraryTogether", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grouping.
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hash.
        /// </summary>
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hide games with no swappable items.
        /// </summary>
        public static string HideGamesWithNoSwappableItems {
            get {
                return ResourceManager.GetString("HideGamesWithNoSwappableItems", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu If the button does not work try here,.
        /// </summary>
        public static string IfButtonDoesntWorkTryHere {
            get {
                return ResourceManager.GetString("IfButtonDoesntWorkTryHere", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import system is currently broken, but it is on the roadmap to be fixed..
        /// </summary>
        public static string ImportSystemCurrentlyBroken {
            get {
                return ResourceManager.GetString("ImportSystemCurrentlyBroken", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Install path.
        /// </summary>
        public static string InstallPath {
            get {
                return ResourceManager.GetString("InstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The install path &quot;{0}&quot; already exists and can&apos;t be added again..
        /// </summary>
        public static string InstallPathAlreadyExists {
            get {
                return ResourceManager.GetString("InstallPathAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu List View.
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replacing dlls on your computer can be dangerous.
        ///
        ///Placing a malicious dll into a game is as bad as running Linking_park_-_nUmB_mp3.exe that you just downloaded from LimeWire.
        ///
        ///Only import dlls from sources you trust..
        /// </summary>
        public static string MalliciousDllsInfo {
            get {
                return ResourceManager.GetString("MalliciousDllsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Multiple {0} DLLs Found.
        /// </summary>
        public static string MultipleDllsFoundTemplate {
            get {
                return ResourceManager.GetString("MultipleDllsFoundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Network Tester.
        /// </summary>
        public static string NetworkTester {
            get {
                return ResourceManager.GetString("NetworkTester", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [NEW DLLs] Found on.
        /// </summary>
        public static string NewDllFoundOn {
            get {
                return ResourceManager.GetString("NewDllFoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New DLLs.
        /// </summary>
        public static string NewDlls {
            get {
                return ResourceManager.GetString("NewDlls", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New DLLs Found.
        /// </summary>
        public static string NewDllsFound {
            get {
                return ResourceManager.GetString("NewDllsFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No DLLs Found.
        /// </summary>
        public static string NoDllsFound {
            get {
                return ResourceManager.GetString("NoDllsFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You have no DLL records to export..
        /// </summary>
        public static string NoDllsToExport {
            get {
                return ResourceManager.GetString("NoDllsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No new updates are available..
        /// </summary>
        public static string NoNewUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoNewUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okay.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oops.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open DLL location.
        /// </summary>
        public static string OpenDllLocation {
            get {
                return ResourceManager.GetString("OpenDllLocation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (optional).
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Original DLL.
        /// </summary>
        public static string OriginalDll {
            get {
                return ResourceManager.GetString("OriginalDll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restore original DLL.
        /// </summary>
        public static string OriginalDllRestore {
            get {
                return ResourceManager.GetString("OriginalDllRestore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please go to the libary page to download new DLLs..
        /// </summary>
        public static string PleaseNavigateLibraryToDownloadDlls {
            get {
                return ResourceManager.GetString("PleaseNavigateLibraryToDownloadDlls", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please open a .
        /// </summary>
        public static string PleaseOpenIssuePartial1 {
            get {
                return ResourceManager.GetString("PleaseOpenIssuePartial1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu new issue.
        /// </summary>
        public static string PleaseOpenIssuePartial2 {
            get {
                return ResourceManager.GetString("PleaseOpenIssuePartial2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu  on the DLSS Swapper GitHub repository and provide the following information in the additional context section..
        /// </summary>
        public static string PleaseOpenIssuePartial3 {
            get {
                return ResourceManager.GetString("PleaseOpenIssuePartial3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to remove &quot;{0}&quot; from DLSS Swapper? This will not make any changes to DLSS files that have already been swapped..
        /// </summary>
        public static string RemoveDlssSwapperGameTemplate {
            get {
                return ResourceManager.GetString("RemoveDlssSwapperGameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Report issue.
        /// </summary>
        public static string ReportIssue {
            get {
                return ResourceManager.GetString("ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DLL has been reset to {0}..
        /// </summary>
        public static string ResetDllToVersionTemplate {
            get {
                return ResourceManager.GetString("ResetDllToVersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Game Folder.
        /// </summary>
        public static string SelectGameFolder {
            get {
                return ResourceManager.GetString("SelectGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select {0} version.
        /// </summary>
        public static string SelectVersionTemplate {
            get {
                return ResourceManager.GetString("SelectVersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Allow Debug DLLs.
        /// </summary>
        public static string SettingsAllowDebugDlls {
            get {
                return ResourceManager.GetString("SettingsAllowDebugDlls", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SDKs sometimes release debug DLLs which allow additional on-screen information to be displayed..
        /// </summary>
        public static string SettingsAllowDebugDllsInfo {
            get {
                return ResourceManager.GetString("SettingsAllowDebugDllsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Allow Untrusted.
        /// </summary>
        public static string SettingsAllowUntrusted {
            get {
                return ResourceManager.GetString("SettingsAllowUntrusted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DLLs are checked if they are trusted in Windows by validating the signature before being swapped into a game folder. If a DLL fails signature validation then it will not be used. It is recommended to keep this off..
        /// </summary>
        public static string SettingsAllowUntrustedInfo {
            get {
                return ResourceManager.GetString("SettingsAllowUntrustedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This only applies to the DLL picker, not the library page..
        /// </summary>
        public static string SettingsApliesOnlyToDllPickerNotLibrary {
            get {
                return ResourceManager.GetString("SettingsApliesOnlyToDllPickerNotLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check for updates.
        /// </summary>
        public static string SettingsCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Diagnostics.
        /// </summary>
        public static string SettingsDiagnostics {
            get {
                return ResourceManager.GetString("SettingsDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DLSS Developer Options.
        /// </summary>
        public static string SettingsDllsDeveloperOptions {
            get {
                return ResourceManager.GetString("SettingsDllsDeveloperOptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable logging to console window.
        /// </summary>
        public static string SettingsEnableLoggingToConsoleWindow {
            get {
                return ResourceManager.GetString("SettingsEnableLoggingToConsoleWindow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable logging to file.
        /// </summary>
        public static string SettingsEnableLoggingToFile {
            get {
                return ResourceManager.GetString("SettingsEnableLoggingToFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game Libraries.
        /// </summary>
        public static string SettingsGameLibraries {
            get {
                return ResourceManager.GetString("SettingsGameLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu General troubleshooting guide.
        /// </summary>
        public static string SettingsGeneralTroubleshootingGuide {
            get {
                return ResourceManager.GetString("SettingsGeneralTroubleshootingGuide", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Give Feedback.
        /// </summary>
        public static string SettingsGiveFeedback {
            get {
                return ResourceManager.GetString("SettingsGiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You can suggest a feature or report a problem or on the DLSS Swapper.
        /// </summary>
        public static string SettingsGiveFeedbackInfo {
            get {
                return ResourceManager.GetString("SettingsGiveFeedbackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Network Tester.
        /// </summary>
        public static string SettingsNetworkTester {
            get {
                return ResourceManager.GetString("SettingsNetworkTester", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Only Show Downloaded DLLs.
        /// </summary>
        public static string SettingsShowOnlyDownloadedDlls {
            get {
                return ResourceManager.GetString("SettingsShowOnlyDownloadedDlls", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show on-screen indicator.
        /// </summary>
        public static string SettingsShowOnScreenIndicator {
            get {
                return ResourceManager.GetString("SettingsShowOnScreenIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Theme Mode.
        /// </summary>
        public static string SettingsThemeMode {
            get {
                return ResourceManager.GetString("SettingsThemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use system setting.
        /// </summary>
        public static string SettingsThemeSystemSettingDefault {
            get {
                return ResourceManager.GetString("SettingsThemeSystemSettingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Troubleshooting.
        /// </summary>
        public static string SettingsTroubleshooting {
            get {
                return ResourceManager.GetString("SettingsTroubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Verbose logging.
        /// </summary>
        public static string SettingsVerboseLogging {
            get {
                return ResourceManager.GetString("SettingsVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Version.
        /// </summary>
        public static string SettingsVersion {
            get {
                return ResourceManager.GetString("SettingsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your current log file is .
        /// </summary>
        public static string SettingsYourCurrentLogfile {
            get {
                return ResourceManager.GetString("SettingsYourCurrentLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sorry.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Starting download.
        /// </summary>
        public static string StartingDownload {
            get {
                return ResourceManager.GetString("StartingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Step 4: Submit your issue.
        /// </summary>
        public static string StepFourSubmitYourIssue {
            get {
                return ResourceManager.GetString("StepFourSubmitYourIssue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Step 1: Create new issue.
        /// </summary>
        public static string StepOneCreateNewIssue {
            get {
                return ResourceManager.GetString("StepOneCreateNewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Step 3: Copy body.
        /// </summary>
        public static string StepThreeCopyBody {
            get {
                return ResourceManager.GetString("StepThreeCopyBody", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Step 2: Copy title.
        /// </summary>
        public static string StepTwoCopyTitle {
            get {
                return ResourceManager.GetString("StepTwoCopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Swap.
        /// </summary>
        public static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Thanks for helping!.
        /// </summary>
        public static string ThanksForHelping {
            get {
                return ResourceManager.GetString("ThanksForHelping", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This title is not manually added and can&apos;t be removed..
        /// </summary>
        public static string TitleNotManuallyAddedCantBeRemoved {
            get {
                return ResourceManager.GetString("TitleNotManuallyAddedCantBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adding top level directory is not supported. Please add the root of your game directory..
        /// </summary>
        public static string TopLevelDirectoryNotSupported {
            get {
                return ResourceManager.GetString("TopLevelDirectoryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to delete {0} record..
        /// </summary>
        public static string UnableToDeleteRecord {
            get {
                return ResourceManager.GetString("UnableToDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to update DLL records..
        /// </summary>
        public static string UnableToDllUpdate {
            get {
                return ResourceManager.GetString("UnableToDllUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View Type.
        /// </summary>
        public static string ViewType {
            get {
                return ResourceManager.GetString("ViewType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please wait for download to complete before swapping.
        /// </summary>
        public static string WaitToDownloadCompleteBeforeSwapping {
            get {
                return ResourceManager.GetString("WaitToDownloadCompleteBeforeSwapping", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu While loading your games some new DLLs have been discovered which are not in the DLSS Swapper manifest..
        /// </summary>
        public static string WhileLoadingYourGameNewDllsDiscoveredHelpUs {
            get {
                return ResourceManager.GetString("WhileLoadingYourGameNewDllsDiscoveredHelpUs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You do not have to submit the DLLs. We will track them down based on the information provided..
        /// </summary>
        public static string YouDoNotHaveToSubmitDllAutoTrack {
            get {
                return ResourceManager.GetString("YouDoNotHaveToSubmitDllAutoTrack", resourceCulture);
            }
        }
    }
}
